### ISSUE TITLE
Attention heat maps

### ISSUE THREAD

**Issue by BLINKSK** [lancopku/SOS#1]
Excuse me, how do you implement the Attention heat maps mentioned in your paper?

**Comment by keven980716** [comment]
Hi! We drew the visualizations of the attention heat maps with the help of the open-sourced tool [bertviz](https://github.com/jessevig/bertviz) and some code from [here](https://github.com/RenShuhuai-Andy/my-tools/blob/master/python_script/visualization/plt_vis.ipynb). We plan to re-organize the code, and push it to the GitHub.

**Comment by keven980716** [comment]
We have provided the code for visualizations in the repo. Hope this can help you.
